# Import libraries
import os
import groq
from groq import Groq
from dotenv import load_dotenv
import json
import sys
from pathlib import Path

# Add root directory to system path for relative imports
root_path = Path(__file__).resolve().parent.parent
sys.path.append(str(root_path))

# Import tools
from tools.web_search import web_search

# Import schemas
from tools.web_search import web_search_schema

# Load environment variables and initialize Groq client
load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY)

def run_conversation(user_prompt, model, messages):
    """Processes a single conversational turn with the Groq API, handling tool execution.

    Appends the new user prompt to the conversation history, sends the context 
    to the specified LLM model, and recursively manages any requested tool calls 
    (like web searches) up to a defined limit before returning the final response.

    Args:
        user_prompt (str): The latest message or command from the user.
        model (str): The identifier of the Groq model to be used.
        messages (list): The persistent conversation history containing previous 
            role and content dictionaries.

    Returns:
        tuple: A tuple containing:
            - str: The final text response generated by the assistant or an error message.
            - list: The updated persistent conversation history including the user's 
                    prompt and the assistant's final response.
    """

    # Add the user's latest prompt to the persistent message history
    messages.append({
        "role":"user",
        "content":user_prompt
    })

    # Create a temporary history array to hold tool calls and tool responses
    # without polluting the main persistent memory
    temporary_messages = []

    for message in messages:
        temporary_messages.append(message.copy())

    # Define the schemas available for the model to use
    tools = [web_search_schema]

    # Map the schema names to the actual executable Python functions
    available_functions = {
        "web_search":web_search,
    }

    # Set a maximum number of consecutive tool-call loops to prevent infinite loops
    search_limit = 5

    for i in range(search_limit):

        try:
            # Request a completion from the Groq API using the temporary context
            response = client.chat.completions.create(
                model=model,
                messages=temporary_messages,
                tools=tools,
                tool_choice="auto",
            )

            response_message = response.choices[0].message
            tool_calls = response_message.tool_calls

            # If the model did not request any tools, it means the final response is ready
            if not tool_calls:

                # Append only the final assistant response to the persistent history
                messages.append({
                    "role":"assistant",
                    "content":response_message.content
                })

                print("[run_conversation] Succesfully")
                return response_message.content, messages

            # If tools were requested, add the model's tool call request to the temporary history
            temporary_messages.append(response_message)

            # Iterate through each tool call requested by the model
            for tool_call in tool_calls:
                function_name = tool_call.function.name
                function_to_call = available_functions[function_name]
                function_args = json.loads(tool_call.function.arguments)

                # Execute the matched local function with the provided arguments
                function_response = function_to_call(**function_args)
                    
                # Add the tool's execution result back to the temporary messages for the next iteration
                temporary_messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": json.dumps(function_response),
                })

        # Handle specific Groq API exceptions to provide clear error messages to the user
        except groq.AuthenticationError as e:
            print("[run_conversation] ERROR 401 AuthenticationError triggered:", e)
            return "Ha fallado la autenticación. Revisá que la API Key esté bien.", messages
            
        except groq.RateLimitError as e:
            print("[run_conversation] ERROR 429 RateLimitError triggered:", e)
            return "Has superado el límite de peticiones. Espera un momento.", messages
            
        except groq.BadRequestError as e:
            print("[run_conversation] ERROR 400 BadRequestError triggered:", e)
            return "Detecte una solicitud invalida. Revisa el retorno de las herramientas vinculadas.", messages
            
        except groq.APIError as e:
            print("[run_conversation] APIError triggered:", e)
            return "Ha ocurrido un error en los servidores de Groq.", messages

        except Exception as e:
            # Catch-all for any other internal system errors (e.g., JSON parsing failures)
            print("[run_conversation] Internal system error triggered:", e)
            return "Ha ocurrido un error interno del sistema.", messages

    # If the loop hits the search limit, exit gracefully
    print("[run_conversation] Search limit exceeded")
    return "He excedido el limite de busquedas establecido. Intenta nuevamente.", messages



